[build]
  command = "pip install -r requirements.txt && gunicorn app:app"

[functions]
  directory = "netlify-functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  PYTHON_VERSION = "3.9"
  FLASK_APP = "app.py"
  FLASK_ENV = "production"

[dev]
  command = "flask run"
  port = 5000